### ISSUE TITLE
Proposal: silverstripe-geshiparser

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverleague.github.io#12]
### why?

It's quite useful as a developer to publish code easily and have it formatted pretty in the frontend. The default "preformatted" feature in the CMS only adds a pre-tag and monospaces it. GeSHiParser adds coloring and line numbering too.

### Functionality

- [X] Convert everything between `[code][/code]` tags to a prettified and more readable html

### Lacking

- [ ] Tests

### Known issues

- If the code to be rendered contains `['code']`, the input from ShortcodeParser breaks on that line and starts a new block.

### Todo

- [ ] Implement BBCode integration module?

### Example output

https://casa-laguna.net/e-log/show/openelec-on-raspberry-pi-running-from-usb

**Comment by robbieaverill** [comment]
Seems like a good idea
