### ISSUE TITLE
Proposal: silverstripe-markdown

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverleague.github.io#3]
# silverleague/silverstripe-markdown

**Specification:** https://silverleague.github.io/draft/silverstripe-markdown

## Introduction

Markdown is a common standard for editing rich text in modern websites.

This module would aim to provide a drop in replacement for a WYSIWYG editor for SilverStripe. It should contain some SilverStripe features such as internal linking and image selectors for inserting assets.

It should use an established markdown parser to generate the preview and render for the frontend. GitHub would be ideal, but requires an external HTTP request. Parsedown might be more suitable.

It should work with SilverStripe 4 and be React friendly.

## Why?

There are a few markdown modules around, but they all have limitations and/or have limited support involvement.

This proposal would establish a new standard for markdown editing in SilverStripe.

It would be a _no-configuration replacement_ for TinyMCE that you'd configure in your site settings. By default, installing the module would come with the required configuration to replace all instances of TinyMCE. In a perfect world, the templating required for rending as HTML would not change from existing TinyMCE markup (e.g. `$Content`). You could switch it back for certain page types via configuration settings in the CMS, and possibly a global "on off" switch it, also in the CMS.

The goal of this would be to help developers to easily get going with an alternative editor, and prove that SilverStripe isn't necessarily as tightly coupled to TinyMCE as people may have thought.

**Comment by fonsekaean** [comment]
Hello @robbieaverill We, SilverStripers (http://silverstripers.com) have made a markdown module which covers these requirements. You are welcome to check it out. https://github.com/SilverStripers/markdownfield

**Comment by robbieaverill** [comment]
Nice!

**Comment by robbieaverill** [comment]
Ok so there's not been any feedback on this, but it is still something I'd like to do.

@fonsekaean does your markdown field have integrations with SilverStripe for things like linking to internal pages, inserting media from the assets area etc? I think those kinds of things are what the existing markdown editor modules for SilverStripe have all been lacking (so far as I've seen) and are something important for us to warrant pushing out a "markdown editor to rule them all" for SilverStripe.

**Comment by fonsekaean** [comment]
Hello @robbieaverill 

Yup it does, you can use the assets and the pages and other media embeds using the module.

**Comment by robbieaverill** [comment]
Cool @fonsekaean! Last question 😛is it a React based editor?

**Comment by fonsekaean** [comment]
@robbieaverill yup it is

**Comment by robbieaverill** [comment]
Ok, it doesn't sound like there's a huge driver for this. https://github.com/SilverStripers/markdownfield apparently works nicely with React in SilverStripe 4 already, no point in reinventing the wheel!
