### ISSUE TITLE
Proposal: silverstripe-async

### ISSUE THREAD

**Issue by assertchris** [silverleague/silverleague.github.io#6]
# silverleague/silverstripe-async

**Specification:** https://silverleague.github.io/draft/silverstripe-async

## Why?

SilverStripe has a traditional, synchronous execution model. Except for [QueuedJobs](https://github.com/silverstripe-australia/silverstripe-queuedjobs), no other supported module offers anything nearly useful for implementing asynchronous execution in places where an application could use it.

A module – which offers an event loop, web sockets, and sane parallel execution – could allow for more interesting and useful extensions to the CMS. This would make things like multi-user editing, presence, parallel queue execution, and DataObject push hooks trivial to implement.

## Details

I propose we use [Amp](https://github.com/amphp). It requires `^7.0`, which would become the required version for this module. It provides a mature event loop, promise, and web socket implementations. It also offers a parallel execution model that depends on Pthreads or PCNTL. 

I suggest we abstract the parallel execution code, and base the first version on `exec` instead (as this will already be used for the initial CronTask (event loop daemon).

> Aspects of this have already been worked into QueuedJobs, but are disabled by default. They are also present in the [Serve module](https://github.com/silverstripe/silverstripe-serve).

## Functionality

- [ ] Create a CronTask to "daemonize" the main event loop process
- [ ] Create interfaces for web socket listener classes
- [ ] Create a "global" web socket listener class, to broadcast DataObject events to subscribed web socket clients
- [ ] Create/embed sane parallel execution scheme
- [ ] Abstract FE web socket code, paving the way for additional modules
- [ ] Propose DataObject push hooks module
- [ ] Propose Presence module
- [ ] Propose "new" multi-user editing module
- [ ] Propose "new" (or changes to existing) queued jobs module, which uses parallel execution by default

**Comment by robbieaverill** [comment]
Great idea! I'd like to take the "advocate" role for this. I'm not familiar enough with async PHP to volunteer for co-maintainer.

**Comment by robbieaverill** [comment]
@assertchris if this is mostly aimed at being a sort of architectural module, perhaps it might be a good idea to add a simple example module with a use case to go along with it - something like a live comments system, etc. Thoughts?

**Comment by robbieaverill** [comment]
@assertchris still keen on doing this?

**Comment by KINKCreative** [comment]
Please look at Swoole PHP extension:

https://www.w3c-lab.com/php-7-1-swoole-v1-9-5-vs-node-js-benchmark-test-php7-swoole-beats-node-js/

https://www.swoole.co.uk/

The light benchmark server handles 200k+ requests / second on a normal box, the range of 12x more than a nodejs async server.

Imagine a completely async server based on that, that would then route the isolated processes via the silverstripe event stack? It could also just layer next to it, but I assume the ORM and file read/write parts (at least, being the biggest IO bottlenecks) would need to be refactored to work async.

And there is also ReactPHP https://reactphp.org/

**Comment by assertchris** [comment]
I find myself in a spot where I don't have time to pursue this. Someone else can pick it up, if it interests them. Until then, I think it best to close the issue.
