### ISSUE TITLE
Proposal: silverstripe-ideannotator

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverleague.github.io#7]
# silverleague/silverstripe-ideannotator

**Specification:** https://silverleague.github.io/draft/silverstripe-ideannotator
**Repository:** https://github.com/axyr/silverstripe-ideannotator

## Why?

The SilverStripe ORM definition with static arrays are unreadable for PHPStorm and NetBeans (and other IDE's), to support auto-completion on properties and methods.

## Details

This module generates @property, @method and @mixin tags for DataObjects, Page_Controllers and (Data)Extensions, so IDE's like PHPStorm recognize the database and relations that are set in the $db, $has_one, $belongs_to, $has_many and $many_many arrays including PropertyID for $has_one relations.

The docblocks can be generated/updated with each dev/build and with a DataObjectAnnotatorTask per module or classname.

## Functionality

- [x] Generate `@property` annotations to models and pages
- [x] Generate `@method` annotations to models and pages
- [x] Generate `@mixn` annotations to models and pages
- [x] Only scan assigned modules

## To do

- [x] SilverStripe 4 support
- [x] Namespaces

**Comment by robbieaverill** [comment]
What's the status on this one?

**Comment by Firesphere** [comment]
SS-4 support is working, only thing is one test is failing for unknown reasons. Other than that, I'm happy to transfer it to the League and make @axyr owner and responsible for PR's

**Comment by Firesphere** [comment]
After a bit of testing, it does need some updates to be fully SS4 compatible, but it's on track and very useful to multiple users.
@axyr What's your thought on the statement above?

**Comment by axyr** [comment]
Hi @Firesphere. At the moment I'm very busy with contract work, so I don't have time for this project.

But feel free to move the repo to the League.

**Comment by Firesphere** [comment]
@axyr I'm not the owner of the repo, so I can't initiate a transfer ;)

**Comment by axyr** [comment]
@Firesphere I have transferred the repository.

I would appreciate it to keep my name in it and maintain the commit history as it is.

Thanks for taking care of the project!

**Comment by Firesphere** [comment]
Obviously!

**Comment by Firesphere** [comment]
Updated the Readme to reflect the change of ownership :)

**Comment by axyr** [comment]
Thanks, looks very nice!

**Comment by Firesphere** [comment]
As accepted, now closed. @axyr will be mentioned as originator and will stay active in support when possible.
IDE Annotations Module now lives at https://github.com/silverleague/silverstripe-ideannotator

Maintainers: @axyr as primary
@firesphere secondary
@robbieaverill as contributor

I expect it to move to a full supported SilverLeague module within a month or two :)

@axyr Very much appreciated, and you're obviously welcome to contribute further!
