### ISSUE TITLE
Proposal: silverstripe-foundation-forms

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverleague.github.io#9]
Foundation is the second most popular CSS framework. It would be good to provide a basic set of templates to support foundation users.

Anyone with good frontend skills willing to pick this up? I'm absolutely _not_ the person for frontend work.

**Comment by robbieaverill** [comment]
For the CMS or the frontend?

**Comment by Firesphere** [comment]
Both this one and the BS4 is for frontend. We don't want to interfere with the backend, right?

**Comment by Firesphere** [comment]
A label "very draft" would almost be in order here :)

**Comment by robbieaverill** [comment]
Is Foundation still common, nearly two years on from this being raised?

It might be cool - as a follow up to the Bootstrap issue (I just closed it) I suggested that the CWP starter theme is likely to continue being the de-facto implementation of Bootstrap for frontend use in SilverStripe. Do you think that a Foundation (or other CSS framework) implementation could be a fork of that, or a standalone module?
